"""empty message

Revision ID: 5ae36d36a3f6
Revises: 4d16d602cfce
Create Date: 2017-08-30 14:25:35.047000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae36d36a3f6'
down_revision = '4d16d602cfce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column(u'shoppinglists', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shoppinglists', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shoppinglists', type_='foreignkey')
    op.drop_column(u'shoppinglists', 'created_by')
    op.drop_table('users')
    # ### end Alembic commands ###
